countries:
  - Egypt
  - Saudi Arabia
  - United Arab Emirates
  - Qatar
  - Kuwait
  - Bahrain
  - Oman
  - Jordan
  - Lebanon
  - Iraq
  - Palestine
  - Syria
  - Yemen
  - Libya
  - Tunisia
  - Algeria
  - Morocco
  - Sudan
  - Mauritania
  - Somalia
  - Djibouti
  - Comoros
